### ISSUE TITLE
Create release tags

### ISSUE THREAD

**Issue by Kern046** [rtfmcorp/asylamba-game#2]
Now that you opened your source code to the wide universe, it would be nice if you can have a good control of the gitflow.

This issue is more an advice than a real issue, but you should establish a proper gitflow, such as `develop` branches, `master`'s protection and release tags to make solid checkpoints in the repository's historic to come !

**Comment by acknowledge** [comment]
Very good advice. I started by adding a tag and a github release on the master branch.

Do you think it's useful to tag previous versions or it's good enough to start from now ?

**Comment by Kern046** [comment]
I think it's really good enough :) !

The issue can be closed !
