### ISSUE TITLE
Implement Composer

### ISSUE THREAD

**Issue by Kern046** [rtfmcorp/asylamba-game#3]
To handle properly dependencies and autoload, no one is better than Composer !

https://getcomposer.org/

You should implement a basic composer.json file !

**Comment by acknowledge** [comment]
Since we do not have any dependencies except jQuery (that is linked via a CDN), is it really necessary ?

**Comment by Stoakes** [comment]
Hi,

Apart from dependencies management, it's a good tool to [manage autoloading](https://getcomposer.org/doc/01-basic-usage.md#autoloading).
In Asylamba's case, it would avoid manual class import and add some standard practices in code.

**Comment by Kern046** [comment]
It is necessary for later dependencies, like PHPUnit or event some cache features or other external libraries that would be implemented in the future.

Toe me, it's also a way to see if you're ready to accept conceptual modifications of the code (not the gameplay, for now), because I don't want to spend many hours on PRs which would be never merged (it happened once, I don't wish to you the same fate X)).

**Comment by acknowledge** [comment]
Yeah ok, I understand.

We're ready to accept contributions. Especially if it's refactoring, simplifying of the launch process, adding tests, creating documentation, and so on. For more in depth modifications like gameplay, it's better to start a discussion on the Asylamba forum first. So yeah, I'm really happy you want to improve things.

**Comment by acknowledge** [comment]
PR merged. Issue closed. Thanks

**Comment by Kern046** [comment]
NB: My commit with the clause "Close #X" closes automatically issues when merged into master :) !

Thanks for the review :D !

**Comment by acknowledge** [comment]
It's what I thought, but after the merge, the issue was still open. 

It's because this was on the dev branch. So it's usual to let issues open until it's merged on master ?

**Comment by Kern046** [comment]
There is nothing really standard in this process, because Github is not concepted yet as a project manager. But on my own projects I tend to use the new Github features instead of Trello ! 

For example, this is a link to one of my projects board : https://github.com/DevelopTech/AgilityBundle/projects/1

The issues are considered as features (or feedbacks) and are closed when deployed !

**Comment by acknowledge** [comment]
Ok, thanks for the precision.

Yes, I heared about this new feature of Github when they published it. I was talking about it with abdelaz3r this morning. We want to reach out every person that want to contribute and organize a virtual meeting to talk about this (ideas of contributions, organization, labels of issues, milestones and so on). Then we'll create the board (GH Project). Would you be interested to attend such a meeting ?

**Comment by Kern046** [comment]
I would be very glad to be in it :) !

EDIT : I'm already on Discord ;)

**Comment by acknowledge** [comment]
Great ! I'll keep you updated.
