### ISSUE TITLE
Les recycleurs donnent plus de ressource que leur capacité

### ISSUE THREAD

**Issue by ChickenStorm** [rtfmcorp/asylamba-game#52]
Les recycleurs donnent plus de ressource que leur capacité théorique.

![](https://cdn.discordapp.com/attachments/263123325893607424/273358179801235457/Screenshot_2017-01-24-08-24-31.png)

![](https://cdn.discordapp.com/attachments/263123325893607424/273358216698789889/Screenshot_2017-01-24-08-41-59.png)

**Comment by acknowledge** [comment]
Ce n'est pas un bug. Il y a une petite valeur aléatoire qui diminue ou augmente les ressources collectées. Il est possible de discuter d'un changement de la façon de faire.
